package tddpart2;
import java.lang.reflect.InvocationTargetException;


public class ExcerciseTestPart2 {  

    public static void main(String[] args) throws Exception{
	new TestCaseTest("testRunning").run();
    new TestCaseTest("testSetUp").run();

    }
   
   	
}
 

